### ISSUE TITLE
KeyError: 'cache_position'

### ISSUE THREAD

**Issue by pictavien** [charlesjin/emergent-semantics#1]
Hi,
I'm trying to repeat your experiment. When executing your `lm_train.sh` script as you specify it in your README, I get the
following error. Do you have an idea about what is happening ? 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/dev/emergent-semantics/lm/train.py", line 805, in <module>
    main()
  File "/dev/emergent-semantics/lm/train.py", line 746, in main
    acc, perplexity, loss = eval(model)
                            ^^^^^^^^^^^
  File "/dev/emergent-semantics/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/lm/train.py", line 550, in eval
    _, correct, total = eval_with_config_and_model(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/lm/eval.py", line 659, in eval_with_config_and_model
    ) = syn_utils.nucleus_sample(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/lm/utils.py", line 184, in nucleus_sample
    outputs = decode_with_grammar(
              ^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/lm/utils.py", line 100, in decode_with_grammar
    model_kwargs = model._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/emergent-semantics/venv/lib/python3.12/site-packages/transformers/generation/utils.py", line 660, in _update_model_kwargs_for_generation
    model_kwargs["cache_position"] = model_kwargs["cache_position"][-1:] + num_new_tokens
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'cache_position'
```

**Comment by charlesjin** [comment]
Thanks for bringing this to my attention. Unfortunately I haven't been able to reproduce this error yet, even with a clean install. Can you tell me what version of Transformers you're using?

For now, you can also try changing this line to ```False```:
https://github.com/charlesjin/emergent-semantics/blob/75e0384a32b001800e2dbeb5cff31b11fe54d893/lm/utils.py#L42

**Comment by pictavien** [comment]
In order to fix the problem I had to downgrade transformers to 4.41.2 but then I got other issues with other packages. 
I will try to get a cleaner install compliant with your environment.yml.

**Comment by pictavien** [comment]
Hi,
I have restarted my installation using your `environment.yml`. In order to use use `tensorboard`, I have used options `--with_tracking` and `--report_to tensorboard`. This time I've got:

>  File "/home/gpoint/progsynth-dev/emergent-semantics/lm/train.py", line 530, in main
    experiment_config = vars(args)
> UnboundLocalError: local variable 'args' referenced before assignment

I have to remove the line 292 from `lm/train.py` that deletes variable `args`. After that I've got:

> File "/home/gpoint/progsynth-dev/emergent-semantics/lm/train.py", line 774, in main
    "eval_loss": eval_loss,
> NameError: name 'eval_loss' is not defined

**Comment by charlesjin** [comment]
Got it. Do you mind trying to run it without tracking? I actually never used that and the code for tracking is left over from the training script I adapted.
